version: '3'

services:
  mongo-db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: messages

  app:
      build:
        context: .
        dockerfile: Dockerfile.dev
      ports:
        - '3000:3000'
      environment:
        - DATABASE_HOST=db
      depends_on:
        - mongo-db
