version: '3'

services:
  mongo-db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: messages

  test-mongo-db:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGODB_DATABASE: messages